import 'package:berita_app/api/api_db.dart';
import 'package:berita_app/helper/theme.dart';
import 'package:berita_app/models/models.dart';
import 'package:berita_app/providers/providers.dart';
import 'package:berita_app/view/widgets/widgets.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_html/flutter_html.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:get/get.dart';
import 'package:provider/provider.dart';
import 'package:share/share.dart';
import 'package:shimmer/shimmer.dart';

part 'home_page.dart';
part 'second_page.dart';
part 'three_page.dart';
part 'four_page.dart';
part 'nointernet_connection_page.dart';
part 'berita_terkini_page.dart';
// part 'by_category_page_old.dart';
part 'category_page_with_appbar.dart';
part 'redaksi_page.dart';
part 'video_page.dart';
part 'detail_page.dart';
part 'category_page.dart';
part 'by_category_page.dart';
